### PR TITLE
Feature cs fixer

### PR DESCRIPTION
**Pull request by mjacobus**
Hello

I took the opportunity that the project has no open PR and ran php-cs-fixer on the project. I also added a script to automatically fix all the php code.

They adopted CS is the same as symfony's (Psr2 + enhancements) with the exception of a few their extra rules.

Cheers!

### CODE REVIEW

**Comment by mjacobus** [comment]
I signed it!

**Comment by kesar** [comment]
It's hard to review a PR like this one ;-) 

Not sure if there is an issue and consensus about what CS rules is following this library.

**Comment by ianbarber** [comment]
I very much like having the cs automatically fixable! The service classes are generated though, I would suggest excluding those and raising an issue for changes needed to the template. Given that the template changes are likely to be a while though, i would minimise the differences to the existing. The biggest one I can see is 4 space indent rather than 2 - could you alter to use a 2 space indent?

**Comment by mjacobus** [comment]
@kesar yeah, I know. Besides this is a unsolicited PR =) You guys do not need to feel bad about not merging this ;). I do feel however, that it is important to follow the [CS](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) widely adopted by the community, since they will be the consumers and potential contributors of the API.

@ianbarber  The goal was that [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) would fix indentation, but it apparently was not consistent. I can try to check if this is configurable to 2 spaces indentation, although I would strongly recommend using 4 to follow the community standards, as mentioned above.

If you guys are willing to merge I can try to make the changes this weekend and modify this PR or create a new one.

Cheers!

**Comment by localheinz** [comment]
@mjacobus 

How about making this part of the build process? 

Here's an example from a different project:

* https://github.com/zendframework/modules.zendframework.com/blob/master/.travis.yml#L31

**Comment by localheinz** [comment]
@mjacobus 

Never mind my example, we've already got a configuration for `phpcs` right here: https://github.com/google/google-api-php-client/blob/master/style/ruleset.xml

**Comment by localheinz** [comment]
@ianbarber @kesar @mjacobus 

Do you want to take a look at #604?

**Comment by bshaffer** [comment]
I would love to move the non-generated parts of the library onto PSR-1 and 2 code standards. However, we are merging `v2-dev` into master for the `2.0` release, and changing this now would be only make the merge process difficult and the diffs harder to read.

We will now track this task in #692

**Pull request closed without merging**
