### PR TITLE
fixes #574 - checks for cachedir trailing slash

### LINKED ISSUE #574: Uncaught exception 'Google_Cache_Exception' with message 'Could not create storage directory
I'm getting the following error while trying the example on https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-php with the latest code:

```
Warning: mkdir(): Permission denied in /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/google-api-php-client-master/src/Google/Cache/File.php on line 149 Fatal error: Uncaught exception 'Google_Cache_Exception' with message 'Could not create storage directory: /var/tmp//Google_Client/d7' in /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/google-api-php-client-master/src/Google/Cache/File.php:154 Stack trace: #0 /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/google-api-php-client-master/src/Google/Cache/File.php(139): Google_Cache_File->getCacheDir('306ab5989d4665e...', true) #1 /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/google-api-php-client-master/src/Google/Cache/File.php(134): Google_Cache_File->getCacheFile('306ab5989d4665e...', true) #2 /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/google-api-php-client-master/src/Google/Cache/File.php(95): Google_Cache_File->getWriteableCacheFile('306ab5989d4665e...') #3 /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/google-api-php-client-master/src/Google/Auth/OAuth2.php(315): Google_Cache_File->set('306ab5989d4665e...', '{"access_token"...') #4 /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/HelloAnalytics.php(31): Google_Auth_O in /mnt/web1/e0/53/44455566/htdocs/myApp123/admin/google-api-php-client-master/src/Google/Cache/File.php on line 154 
```
After investigation I found the issue in file "google-api-php-client-master/src/Google/Cache/File.php"  in function "getCacheDir($file, $forWrite)". The storage directory is created like:
```
$storageDir = $this->path . '/' . substr(md5($file), 0, 2);
```
But the error in my case is the concatenated slash after the path. It already contains a slash! Refer to error message:
```
/var/tmp//Google_Client/d7'
```
After the "tmp" folder there are 2 slashes now that raises the error. If I remove the concatenation of this slash, it works fine.

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by Nyholm** [comment]
This does not support windows operation systems. They use '\' instead of '/'. 

I suggest to change to something like: 
```php 
private function getCacheDir($file, $forWrite)
{
  // use the first 2 characters of the hash as a directory prefix
  // this should prevent slowdowns due to huge directory listings
  // and thus give some basic amount of scalability
  $storageDir = rtrim($this->path, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . substr(md5($file), 0, 2);

// ...
```

**Comment by bshaffer** [comment]
Windows has [accepted the forward slash since Windowns NT](https://books.google.com/books?id=6QZ6AgAAQBAJ&pg=SA6-PA5&lpg=SA6-PA5&dq=%22while+windows+nt+supports+both+forward+and+reverse+slashes%22&source=bl&ots=Jr3JOT1Uq5&sig=37kEx6vGEmbtIYSzQk91P5Y_iCw&hl=en&sa=X&ved=0ahUKEwjX8rvPv5_JAhVKbD4KHS-KDPIQ6AEIIDAB#v=onepage&q=%22while%20windows%20nt%20supports%20both%20forward%20and%20reverse%20slashes%22&f=false). But I do like your solution better.

**Comment by Nyholm** [comment]
Okey. Thank you for the link. I did not know that.

**Comment by tmatsuo** [comment]
LGTM

**Pull request merged**
