### PR TITLE
Remove unused parameter $storageFile in unlock method

### PR DESCRIPTION
**Pull request by jordi12100**

### CODE REVIEW

**Comment by jordi12100** [comment]
I signed it!

**Comment by jordi12100** [comment]
Fixes #769

**Comment by bshaffer** [comment]
We need to remove the parameter from [calls that are still passing it in](https://github.com/google/google-api-php-client/blob/master/src/Google/Cache/File.php#L84).

**Comment by jordi12100** [comment]
Yes you're right. I've removed the parameters from the usages.

**Comment by bshaffer** [comment]
LGTM!

**Comment by caleblloyd** [comment]
RE: the change made on: https://github.com/google/google-api-php-client/blob/master/src/Google/Cache/File.php#L76

it seems to me that this statement now has no effect, since the output is not assigned to a variable. did you mean to leave it as:

    $data =  unserialize($data);

**Comment by bshaffer** [comment]
thank you @caleblloyd! This is now fixed in 20e6a625a0dbf0f41815baa565549d9af39c5586

**Pull request merged**
