### PR TITLE
Add Placeholder and required attr

### PR DESCRIPTION
**Pull request by Assimilationstheorie**

### CODE REVIEW

**Comment by bshaffer** [comment]
Would you like to add `required` to `index.php` or any other samples?

**Comment by Assimilationstheorie** [comment]
I would add it to all other files, yes.

**Comment by Assimilationstheorie** [comment]
Deal or no deal?

**Comment by bshaffer** [comment]
Please add the other files to this PR so we encapsulate all the changes in a single commit and pull request!

**Pull request merged**
