### PR TITLE
Don't try to convert to model if alt=media present

### PR DESCRIPTION
**Pull request by sqrrrl**
One more fix for media downloads -- don't set the expected return class so that the raw body is returned.

### CODE REVIEW

**Comment by bshaffer** [comment]
Thank you for this! Question - shouldn't these types of API calls not even set an expected class? Is there somewhere in our documentation we can point for this use-case?

**Comment by sqrrrl** [comment]
The alt parameter is, literally, to request an alternate representation. The default is JSON, but some APIs like Drive and others have resources that have multiple representations -- JSON for metadata, blobs for content. Same for storage and a few others.

In those cases, the methods do have an expected class when the default JSON representation is used. But for media representations, it doesn't make sense to use them.

**Comment by SurferJeffAtGoogle** [comment]
Can we update a test to exercise this new code path?

**Comment by bshaffer** [comment]
merged in #732

**Pull request closed without merging**
