### PR TITLE
Remove a useless isset

### PR DESCRIPTION
**Pull request by OlivierBarbier**
No need to call isset twice.

### CODE REVIEW

**Comment by OlivierBarbier** [comment]
I signed it!

**Comment by quantumpacket** [comment]
```php
if (isset($result['error'], $result['error']['errors'])) {
```
Should just be:
```php
if (isset($result['error']['errors'])) {
```

For `$result['error']['errors']` to exist it already implies that `$result['error']` would already exist. Right?

**Comment by OlivierBarbier** [comment]
Right.

**Comment by bshaffer** [comment]
agreed, let's go with @quantumpacket's solution.

**Comment by bshaffer** [comment]
closing, this will be refactored out soon

**Pull request closed without merging**
