### PR TITLE
adds 1-second leeway to JWT validation to prevent intermittent except…

### PR DESCRIPTION
**Pull request by bshaffer**
…ions

### CODE REVIEW

**Comment by Kak3n** [comment]
Should it be fixed in newest version?

**Comment by bshaffer** [comment]
@Kak3n [v2.0.0-RC5](https://github.com/google/google-api-php-client/releases) and on have had this change.

**Comment by Kak3n** [comment]
thanks ok.

2016-05-25 18:49 GMT+02:00 Brent Shaffer <notifications@github.com>:

**Comment by YuanXiong** [comment]
On my server, the system time is 2 min prior to the current time so I got this problem. The system admin may have to run the ntp service for date updates.

**Comment by jslewis90** [comment]
Mine shows 5 hours later than what what the Google Token returns.

**Comment by bshaffer** [comment]
@jslewis90 I imagine this is an issue with your server's date/time configuration.

**Comment by martinfree** [comment]
Now is impossible to set leeway. Please rollback this fix.

**Comment by bshaffer** [comment]
@martinfree You're right, this is not an optimal solution because it pollutes global scope. I'll submit a fix that ensures the adjustment is localized. It would be great if the `Firebase\JWT` class made leeway configurable per instance as well as statically.

**Comment by martinfree** [comment]
@bshaffer thank you for considering my suggestion. Cheers.

**Comment by hamzawain7** [comment]
In google-api-php-client/src/Google/AccessToken/Verify.php line 213 you are not adding 1 to JWT leeway like you mentioned in comments but rather setting it to one. Kindly fix it.
`
if (property_exists($jwtClass, 'leeway')) {
            // adds 1 second to JWT leeway
            // @see https://github.com/google/google-api-php-client/issues/827
            $jwtClass::$leeway = 1;
        }

`

**Comment by dyegonery** [comment]
This solution didn't worked with me. So, I tried adding 60 seconds to JWT leeway:
if (property_exists($jwtClass, 'leeway')) {
// adds 1 second to JWT leeway
// @see #827
$jwtClass::$leeway += 60;
}

**Comment by FG-Developer** [comment]
Hello,

I have that same problem me too, The problem is solving when i changing $leeway variable value as "+=60", but i do not want change in core file of package. But i don't find any way overwrite this variable on another place.

There is any way changing that variable another place?

**Comment by TheMorganHub** [comment]
I'm sorry for the sarcasm that's about to come, but @hamzawain7 is right. The "geniuses" that "fixed" this are not **adding** to the leeway, but instead they're overwriting whatever value you set to it. For now having to manually edit the vendor files will have to do, although a fix would be appreciated. Thanks.

**Comment by perials** [comment]
@FG-Developer You can pass a custom JWT object to `Google_Client`.
```
$jwt = new \Firebase\JWT\JWT;
$jwt::$leeway = 60; // adjust this value

// we explicitly pass jwt object whose leeway is set to 60
$this->client = new \Google_Client(['jwt' => $jwt]);
```
Refer [this](https://perials.com/login-google-using-php-google-php-client/#fix-for-before-valid-exception) post.

**Pull request merged**
