### PR TITLE
Update the Google HTTP Request class to use the `arg_seperator` in the http_build_query call

### PR DESCRIPTION
**Pull request by chriscct7**
Solves https://github.com/google/google-api-php-client/issues/1046 for the legacy version

### CODE REVIEW

**Comment by chriscct7** [comment]
I signed it!

**Comment by owneroverall** [comment]
Hello geller feller

Den 17:31 tor 1 sep 2016googlebot <notifications@github.com> skrev:

**Comment by bshaffer** [comment]
It would be great to have test coverage for this.

**Comment by chriscct7** [comment]
So I'm thinking for a test, as opposed to testing this exact case, we could ini_set the value to `&amp` in like the bootstrap, because hypothetically, if everything is working correctly nothing should fail if that is done. Or did you have a specific approach in mind?

**Comment by bshaffer** [comment]
I'd rather do this:

```php
// tests/Google/AccessToken/VerifyTest.php
//...
public function testHttpBuildQuery()
{
    $argSeparatorOutput = ini_get('arg_separator.output');
    ini_set('arg_separator.output', '&amp;');
    // do test 
    ini_set('arg_separator.output', $argSeparatorOutput);
}
//...
```

**Comment by bshaffer** [comment]
@chriscct7 alternatively, you can give me [collaboration access to your fork](https://github.com/blog/2247-improving-collaboration-with-forks) and I'll make the change.

**Comment by chriscct7** [comment]
@bshaffer sorry for the delay. I've enabled the edit from maintainers and have added unit tests for both the normal and `&amp;` values of the arg_seperator. Unit test and fixes have been verified against an unfixed fork of repo that was update with tests.

**Comment by bshaffer** [comment]
Sorry for the delay as well! Merged, thank you.

**Comment by chriscct7** [comment]
Not a problem!

**Pull request merged**
