### PR TITLE
Update docs to install latest 2.x version

### PR DESCRIPTION
**Pull request by siburny**

### CODE REVIEW

**Comment by siburny** [comment]
I signed it!

**Comment by siburny** [comment]
The best way is not to specify version at all, so the latest could be installed.

**Comment by mattwhisenhunt** [comment]
Hi @siburny 👋
Thanks for the suggestion and maybe it is superfluous but we want to have the context there that it is not versions 1 or 3.

**Comment by siburny** [comment]
I should've been more clear why I proposed this change. If you run the exact command from the docs
```
composer require google/apiclient:^2.0
```
composer will install version 2.0.0. However, the latest one is 2.2.2 (at the moment).

If you prefer not to specify the minor (.x) version in the docs, then we should use the following:
```
composer require google/apiclient:2.*
```

**Comment by siburny** [comment]
My php and composer versions 
```
c:\Downloads\>php -v
PHP 7.2.8 (cli) (built: Jul 18 2018 10:03:02) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0alpha1, Copyright (c) 2002-2018, by Derick Rethans

c:\Downloads\>composer -V
Composer version 1.7.1 2018-08-07 09:39:23
```

**Comment by mattwhisenhunt** [comment]
Just so we are on the same page what does the following output?
```batch
mkdir testdir
cd testdir
..\composer require google/apiclient:^2.0
..\composer show
```

**Comment by siburny** [comment]
Of course. Here is the output on my dev machine:
```
c:\Downloads\testdir>composer require google/apiclient:^2.0
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.2.3): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.2.0): Loading from cache
  - Installing phpseclib/phpseclib (2.0.11): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing firebase/php-jwt (v3.0.0): Loading from cache
  - Installing google/apiclient-services (v0.64): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing google/auth (v0.8): Loading from cache
  - Installing google/apiclient (v2.0.0): Loading from cache
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
google/apiclient suggests installing tedivm/stash (For caching certs and tokens (using Google_Client::setCache))
Writing lock file
Generating autoload files

c:\Downloads\testdir>composer show
firebase/php-jwt          v3.0.0 A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should confor...
google/apiclient          v2.0.0 Client library for Google APIs
google/apiclient-services v0.64  Client library for Google APIs
google/auth               v0.8   Google Auth Library for PHP
guzzlehttp/guzzle         6.2.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises       v1.3.1 Guzzle promises library
guzzlehttp/psr7           1.2.3  PSR-7 message implementation
monolog/monolog           1.23.0 Sends your logs to files, sockets, inboxes, databases and various web services
phpseclib/phpseclib       2.0.11 PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, S...
psr/cache                 1.0.1  Common interface for caching libraries
psr/http-message          1.0.1  Common interface for HTTP messages
psr/log                   1.0.2  Common interface for logging libraries
```

Also, here is the content of the created `composer.json` (notice the missing caret symbol):
```
{
    "require": {
        "google/apiclient": "2.0"
    }
}
```

**Comment by mattwhisenhunt** [comment]
This just hit me this morning.

Let's change this to add a note that DOS users need to escape the escape character: `composer require google/apiclient:^^2.0`

**Comment by siburny** [comment]
Unfortunately, `composer require google/apiclient:^^2.0` command produces the same results:
```
firebase/php-jwt          v3.0.0 A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should confor...
google/apiclient          v2.0.0 Client library for Google APIs
google/apiclient-services v0.64  Client library for Google APIs
google/auth               v0.8   Google Auth Library for PHP
guzzlehttp/guzzle         6.2.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises       v1.3.1 Guzzle promises library
guzzlehttp/psr7           1.2.3  PSR-7 message implementation
monolog/monolog           1.23.0 Sends your logs to files, sockets, inboxes, databases and various web services
phpseclib/phpseclib       2.0.11 PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, S...
psr/cache                 1.0.1  Common interface for caching libraries
psr/http-message          1.0.1  Common interface for HTTP messages
psr/log                   1.0.2  Common interface for logging libraries
```

**Comment by siburny** [comment]
So after trial and error, I found the right command: you need to include "quotes" around version number
```
composer require google/apiclient:"^2.0"
```
which will produce correct results:
```
firebase/php-jwt          v5.0.0 A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should confor...
google/apiclient          v2.2.2 Client library for Google APIs
google/apiclient-services v0.64  Client library for Google APIs
google/auth               v1.3.2 Google Auth Library for PHP
guzzlehttp/guzzle         6.3.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises       v1.3.1 Guzzle promises library
guzzlehttp/psr7           1.4.2  PSR-7 message implementation that also provides common utility methods
monolog/monolog           1.23.0 Sends your logs to files, sockets, inboxes, databases and various web services
phpseclib/phpseclib       2.0.11 PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, S...
psr/cache                 1.0.1  Common interface for caching libraries
psr/http-message          1.0.1  Common interface for HTTP messages
psr/log                   1.0.2  Common interface for logging libraries
```

**Pull request merged**
