### PR TITLE
Support for JWT v4

### PR DESCRIPTION
**Pull request by john-main-croud**

### CODE REVIEW

**Comment by john-main-croud** [comment]
I signed it!

**Comment by owneroverall** [comment]
Minus 2 slick 2 a mother fucka.

Den 13:05 tis 13 sep 2016John Main <notifications@github.com> skrev:

**Comment by shakaran** [comment]
Duplicate of #1063 even if this PR was more old, since this fail the travis, this probably could be closed

**Comment by bshaffer** [comment]
This was added in https://github.com/google/google-api-php-client/pull/1082

**Pull request closed without merging**
