### PR TITLE
Update MediaFileUpload.php

### PR DESCRIPTION
**Pull request by tibee**
Typo in source.

### CODE REVIEW

**Comment by tibee** [comment]
I signed it!

**Comment by bshaffer** [comment]
When using double quotes for string values, array keys are referenced without the quotes.

**Comment by tibee** [comment]
Certainly not.

It makes PHP Notice.
See manual:
http://en.php.net/manual/en/language.types.array.php#language.types.array.foo-bar

```
PHP Notice:  Use of undefined constant domain - assumed 'domain'.
PHP Notice:  Use of undefined constant message - assumed 'message'.
```

**Comment by tibee** [comment]
Correct link:
http://www.php.net/manual/en/language.types.array.php#language.types.array.foo-bar

**Comment by thejaswip** [comment]
i agree with tibee ! please kindly review

**Pull request closed without merging**
