### PR TITLE
for raw response: fix alt=media detection

### PR DESCRIPTION
**Pull request by Fneufneu**
getUri()->getQuery("alt") return `alt=media` not `media`
$isJson is correct with this change

### CODE REVIEW

**Comment by Fneufneu** [comment]
I signed it!

**Comment by Fneufneu** [comment]
I signed it!

**Comment by bshaffer** [comment]
@Fneufneu Good catch that this will not work.  However, we can make this more robust/accurate:

```php
$isJson = true;
if ($request && $qs = $request->getUri()->getQuery()) {
    parse_str($qs, $query);
    if (isset($query['alt']) && $query['alt'] == 'media') {
        $isJson = false;
    }
}
```

**Comment by bshaffer** [comment]
closing in favor of #876

**Pull request closed without merging**
