### PR TITLE
Initial Compute Engine credentials for #457.

### PR DESCRIPTION
**Pull request by jonparrott**
Still needs tests

### CODE REVIEW

**Comment by ianbarber** [comment]
Thanks! I would do a separate test, and make sure to skip it if not running on compute engine I guess.

**Comment by jonparrott** [comment]
Will do tomorrow or Friday. I should be able to mock the http call to the
metadata server. Thanks!

**Comment by jonparrott** [comment]
Added the tests - pretty straightforward as I mostly adapted the tests from the regular OAuth2 test cases. @ianbarber PTAL, let me know if there's anything else needed here. Additionally, I can add an example if desired.

**Comment by ianbarber** [comment]
Looks good to me, thanks Jon!

**Comment by jonparrott** [comment]
No problem!

**Pull request merged**
