### PR TITLE
fixes undefined buildPsr7Response bug (#864)

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tmatsuo** [comment]
LGTM

**Comment by flaveris** [comment]
Hey guys,

thank you for the fix. But it's still not working for me. I use GuzzleHttp 5 (can't use version 6 because my other dependencies).

Attempted to load class "Response" from namespace "Psr\Http\Message".
Did you forget a "use" statement for e.g. "GuzzleHttp\Message\Response", "DZunke\SlackBundle\Slack\Client\Response", "Buzz\Message\Response", "Symfony\Component\BrowserKit\Response", "Symfony\Component\HttpFoundation\Response" or "GuzzleHttp\Psr7\Response"?
500 Internal Server Error - ClassNotFoundException (Symfony 2.7 framework)
in vendor\google\apiclient\src\Google\Http\REST.php at line 84

And I cannot see any Response class in Psr\Http\Message.

Do you have any thoughts on this?

**Comment by bshaffer** [comment]
@flaveris see #880

**Comment by flaveris** [comment]
@bshaffer Thanks for a quick fix!

**Pull request merged**
