### PR TITLE
Updating Dfareporting.php

### PR DESCRIPTION
**Pull request by jimper**
Adding an updated DCM API service definition to address #803.

### CODE REVIEW

**Comment by bshaffer** [comment]
These files are auto-generated, so this change will not take.

**Comment by noxomatic9000** [comment]
Does that mean it won't be updated to support the DCM API v2.3? Or does it mean that the update to the new API version will happen automatically before the sunset date on february 29?

**Comment by bshaffer** [comment]
It means it'll be updated when the script is manually run to update all the APIs. It's not a great solution, but it's all we have right now.

For those who need it sooner can implement the changes in this pull request.

**Comment by noxomatic9000** [comment]
Thanks for the info. Will the API update be available before the sunset date? Also will it be available in the v1 branch?

**Comment by swordbeta** [comment]
@bshaffer _When_ will you manually run the script to update all the APIs? I don't really wanna fork and apply the changes myself.

**Comment by bshaffer** [comment]
these have been updated for `v1-master` (see #834), and the PR for `master` is here: #835 

I won't be merging these changes into `master` because they break BC. I will need to tag a stable release (`2.0.0`) first, and then I can merge them in. This will probably be in a week or two. So if you need this, just pull down my personal fork and use that.

**Comment by bshaffer** [comment]
this has now been merged into the `master` branch

**Pull request closed without merging**
