### PR TITLE
Make property protected and add getter for it

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Make `pagespeedapi` property protected and add public getter for it

### CODE REVIEW

**Comment by Nyholm** [comment]
:+1:

**Comment by bshaffer** [comment]
These files are auto generated so this change would just be overwritten on the next update

**Comment by bocharsky-bw** [comment]
@bshaffer So how to do this changes and avoid overwriting on the next update?

**Comment by bocharsky-bw** [comment]
Well, for now I just want to improve code quality here.

**Comment by bshaffer** [comment]
I see. I agree with the change, but as this is auto-generated, the work for this change may not be worth the investment. However, the code to generate these classes can be found [here](https://github.com/google/apis-client-generator) if you're interested in implementing a more permanent fix.

**Comment by bocharsky-bw** [comment]
Yea, it'll be a bit hard this way. Thanks for explanation how it works.

**Pull request closed without merging**
