### PR TITLE
Update REST.php

### PR DESCRIPTION
**Pull request by mavelar**
Validate response code if is >= 500, I suggest to handle in our side if a 4xx error code or less happens.

### CODE REVIEW

**Comment by mavelar** [comment]
I signed it!

**Comment by bshaffer** [comment]
I'm not sure why the original author of this code wanted to retry `400`-level errors. I cannot think of a scenario where this would be appropriate.

**Comment by bshaffer** [comment]
I think this is unintended behavior. We do want to throw an exception for `400`-level errors, so the fix above is not quite what we're looking for.

**Comment by tmatsuo** [comment]
Re: retry on 40x

Some cases (I think only) for 403, it's recommended.

Example:
https://developers.google.com/analytics/devguides/reporting/core/v3/errors

> 403	userRateLimitExceeded: Retry using exponential back-off. You need to slow down the rate at which you are sending the requests.

**Comment by bshaffer** [comment]
This would be more exponential backoff than retry though, and is a special case.

**Pull request closed without merging**
