### PR TITLE
Google_Http_MediaFileUpload::chunkSize make settable

### PR DESCRIPTION
**Pull request by dmitrydymarchuk**
I'm receiving chunked data with different size from some service and I would like to upload max available part of those chunks (multiple 262144 b),  but I can't set the `chunkSize` for every step of resumable upload.

### CODE REVIEW

**Comment by bshaffer** [comment]
@dmitrydymarchuk have you noticed you can specify chunk size [in the constructor](https://github.com/google/google-api-php-client/blob/master/src/Google/Http/MediaFileUpload.php#L81)?

**Comment by dmitrydymarchuk** [comment]
Yes, I have, but I need to set different chunkSize for every step and recall constuctor for this is bad way.

**Comment by bshaffer** [comment]
What is the use-case behind having to set a different chunkSize for each step?

**Comment by max-voloshin** [comment]
@bshaffer it allows to use Google API more efficiently (without extra API calls) in case when we import different chunks of data from external sources and we don't know quantity and size of these chunks from the beginning.

**Comment by bshaffer** [comment]
Have you tested and verified that setting the chunk size in this way effectively alters the HTTP request to allow for the functionality you're describing?

**Comment by max-voloshin** [comment]
@bshaffer sure, we upload over 1 GB data to Google Analytics data set with different size of chunks.
Note: we don't have ability to buffer external data in order to use equal size of chunks.

**Pull request merged**
