### PR TITLE
use correct get process user function

### PR DESCRIPTION
**Pull request by kunit**
see #846

### CODE REVIEW

**Comment by bshaffer** [comment]
Hmm... throwing an exception is worse than the problems this is trying to solve. If `get_current_user` returns nothing, we can `md5` the empty string.

Did you run into an error where you used `sudo` and then later couldn't access the files as a web user?

**Comment by kunit** [comment]
Test Program(test.php) owner 'develop'.

```
require_once '/path/to/your-project/vendor/autoload.php';

umask(0);
$cache = new Google_Cache_File(__DIR__ . '/test');
$cache->set('test', '123');
```

run script use original Google_Cache_File, raise error.
same name directory create, because get_current_user() returns same value 'develop'.

```
develop% sudo php test.php
develop% php test.php
PHP Warning:  mkdir(): Permission denied in /path/to/your-project/src/Google/Cache/File.php on line 176
```

**Comment by bshaffer** [comment]
great! thank you for that. If you remove the exception, I will merge this.

**Comment by kunit** [comment]
remove the exception, change log-level.

**Pull request merged**
