### PR TITLE
Update google/auth requirement, remove invalid version constraint

### PR DESCRIPTION
**Pull request by maxdlx**

### CODE REVIEW

**Comment by maxdlx** [comment]
signed

**Comment by bshaffer** [comment]
this pull request accomplishes nothing... the "v" is not taken into account by composer. What are you trying to accomplish?

**Comment by bshaffer** [comment]
I see now, from your comment on #768. Thank you.

**Comment by bshaffer** [comment]
reverted - the CLA was not signed

**Comment by bshaffer** [comment]
fixed in 305fd9c43ccc7921ab71cd848b0420c3e8f620fd

**Pull request merged**
