### PR TITLE
ExpiredException didn't have the correct namespace

### PR DESCRIPTION
**Pull request by danielmirchandani**
See issue #916.

### CODE REVIEW

**Comment by bshaffer** [comment]
Unfortunately this is not that simple. as this library supports `v2.0` of firebase as well, which [does not use the namespace](https://github.com/firebase/php-jwt/blob/v2.2.0/Exceptions/ExpiredException.php)

**Comment by bshaffer** [comment]
It would be best to do the following:

```php
use Firebase\JWT\ExpiredException as ExpiredExceptionV3;

//and then below

try {
    //...
} catch (ExpiredException $e) {
    //...
} catch (ExpiredExceptionV3 $e) {
    //...
}
```

**Comment by danielmirchandani** [comment]
I've updated the pull request based on your comments.

**Comment by bshaffer** [comment]
added in bb90330039782d1dbcfd8a560740efd032ee4283

Thanks!

**Pull request closed without merging**
