### PR TITLE
removes stash logic, adds caching test for MemoryCache

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by bshaffer** [comment]
Yet another way to solve #1075 

This is my preferred method. That way, users can handle `tedivm/stash` at their own risk.  However this leaves us w/o a recommended way use file caching.

**Comment by tmatsuo** [comment]
sounds good too

**Comment by mwithheld** [comment]
Docs on the GitHub main page (README.md) should be updated: remove the reference to Stash, replace with an example for MemoryCache.  Please include a link to the MemoryCache source.

**Comment by bshaffer** [comment]
Would you mind filing an issue for this and we will get the readme updated?

**Pull request merged**
