### PR TITLE
ensures refresh token is added back to the access token, adds tests

### PR DESCRIPTION
**Pull request by bshaffer**
addresses issue #1064

### CODE REVIEW

**Comment by tomaspinho** [comment]
looks great! thanks for the response ;)

**Comment by jonnywilliamson** [comment]
Sorry a little confused here.

If I have a `refresh_token` and pass it to the client along with the `access_token`, and the client detects that the `access_token` is expired and magically/automatically gets me a NEW one using the `refresh_token`...

Why would you need to get the `refresh_token` returned to you again? Surely it doesn't expire (unless revoked?)

Did I misunderstand that PR #1121 ?

**Comment by stevenscg** [comment]
Many refresh tokens do expire, though typically after a large amount of time (weeks, months, years, etc). Also for some systems, the refresh token may be expired after it has been used once. I can't remember if that is per the spec or not.

I ran into the lack of refresh token issue immediately when I started using this library to access the gmail API in "offline" mode (or whatever it is called).

**Comment by jonnywilliamson** [comment]
OK,

I must have been confused when I saw this note at the bottom on the google oauth playground:

image

**Comment by jonnywilliamson** [comment]
>I ran into the lack of refresh token issue immediately when I started using this library to access the gmail API in "offline" mode (or whatever it is called).

I think a lot of people miss the fact that the `refresh_token` is only ever issued at the VERY start when the oauth has been complete for the first time.

It's like you're only chance to grab it and save it for later use. I think a lot of people believe it should be returned to them on every request, but that's not what google does....at least when I was making my app a year or so ago!

**Comment by mikejichaow** [comment]
Can someone help verify when did this get fix? looks like the current commit is after v2.1.0. What's the plan to have another release? I'd love to have a new release asap since I don't have access to install composer yet. Thanks!

**Comment by bshaffer** [comment]
@mikejichaow I have been waiting for confirmation that this fix worked before tagging a new release.

**Comment by mikejichaow** [comment]
@bshaffer Hey, I thought you guys made tests already. Is there anyway I can get the composer processed autoload files so I can test it? Also, is there a way to set the parameter on how long does the token expire? I know on default its always 3600.

**Comment by bshaffer** [comment]
@mikejichaow Install composer and do the following:

```
cd /path/to/my-project
composer install google/apiclient:dev-master
```

Then in your project you can include the autoloader:


```php
# /path/to/my-project/index.php
require_once __DIR__ . '/vendor/autoload.php';
```

**Comment by mikejichaow** [comment]
@bshaffer I've been trying to get composer working but got the following errors:
` Problem 1
    - The requested package google/apiclient No version set (parsed as 1.0.0) is satisfiable by google/apiclient[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.`
  `Problem 2
    - The requested package minimum-stability could not be found in any version, there may be a typo in the package name.`
What are the settings I should use for composer.json?

**Comment by bshaffer** [comment]
Try setting the version as `^2.0`: 

```sh
composer require google/apiclient:^2.0
```

**Comment by bshaffer** [comment]
@mikejichaow you can also now download the release manually [here](https://github.com/google/google-api-php-client/releases/tag/v2.1.1)

**Comment by mikejichaow** [comment]
Got it. Thank you. 
To test it though, is there a way to set expiration time to be shorter/longer? I tried to just call fetchAccessTokenWithRefreshToken before it expires. It passed and logged in but did not seem to update the token. Even though the file modified time is changed which means it got written to. The token is still the same. Will it only got updated after 3600 s?

**Comment by bshaffer** [comment]
@mikejichaow there is no way to change the access token expiration, as it comes from the Google oauth server. You could try hacking the cache file and manually changing the expire time, but I'd say just wait 3600 seconds :=P

**Comment by Micle86** [comment]
bshaffer я считаю что файл должен содержать refresh token

**Comment by bshaffer** [comment]
@Micle86 Я считаю, что это делает !

**Comment by aaronhatton** [comment]
I have updated using Composer and have also downloaded the release manually and am still having issues, please can you advise. Error message I am getting daily is:

`Fatal error: Uncaught LogicException: refresh token must be passed in or set as part of setAccessToken`

**Comment by mikejichaow** [comment]
@arronhatton did u check if you have the refresh token for the first time u make a call? and the second time (after expired) you should call again and it will give u back the refresh token. my test using it works fine now.

**Comment by aaronhatton** [comment]
Found my issue, was using OAuth 2.0 for web server instead of server to server

**Pull request merged**
