### PR TITLE
refactors tests to match class names

### PR DESCRIPTION
**Pull request by bshaffer**
* refactors tests to match class names
* removes `tests/general/AuthTest.php` because the functions being tested are part of the [firebase-jwt](https://github.com/firebase/php-jwt/) library, and not this library.
* removes `tests/testdata/*.pem`, `tests/testdata/*.p12`, and  `tests/testdata/*.json` because these were only being used by `tests/general/AuthTest.php`, which has been removed.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
LGTM, but before I merge, can you update the description to summarize why some files were deleted.

**Comment by bshaffer** [comment]
@tbetbetbe good call. Updated. Would you like me to update the commit message as well?

**Comment by tbetbetbe** [comment]
Yes, that would be nice as well.

**Comment by bshaffer** [comment]
done

**Pull request merged**
