### PR TITLE
update firebase/php-jwt to 4.0

### PR DESCRIPTION
**Pull request by ashbeats**

### CODE REVIEW

**Comment by ashbeats** [comment]
ok. it's signed.

**Comment by bshaffer** [comment]
Is there a specific reason you need Firebase `4.0`?

**Comment by boredom2** [comment]
I need it:-)
The Microsoft Azure SDK has been updated and is only compatible with JWT 4.0 now.
So its really complicated to include Google and Azure with different dependencies for this Lib.

**Comment by ashbeats** [comment]
I'm using laravel/spark, which requires firebase v4.0.

**Comment by tomschlick** [comment]
Another request for this from another laravel/spark user. Can't upgrade spark without it.

Doesn't look like there are any breaking changes in the `3.0`->`4.0` migration so are there any reasons not to upgrade?

**Comment by etremblay** [comment]
This PR would be very appreciated !

**Comment by bshaffer** [comment]
This change will not have an affect as long as `google/auth` requires `~3.0`. This change should fix that: https://github.com/google/google-auth-library-php/pull/137. I will merge this as soon as this is tagged and updated

**Comment by tomschlick** [comment]
Any update? google/google-auth-library-php#137 has been merged.

**Comment by bshaffer** [comment]
This was merged into master in #1082

**Pull request closed without merging**
